### ISSUE TITLE
working

### ISSUE THREAD

**Issue by rpotter12** [rajeshsharma98/library-management-system-python-#1]
Is this project is still working??

**Comment by rajeshsharma98** [comment]
Hope so.....if u are getting any problem in between, you are free to ask !

**Comment by rpotter12** [comment]
I have tried to execute this project by giving command `python3 login_register.py`
![Screenshot from 2019-07-02 14-58-03](https://user-images.githubusercontent.com/34352567/60501834-51c24300-9cda-11e9-86aa-f195fd929175.png)
then I tried to install PIL again I was getting an error
![Screenshot from 2019-07-02 15-02-47](https://user-images.githubusercontent.com/34352567/60501931-7dddc400-9cda-11e9-9f7f-65a1baf71f15.png)
I was searching for how to install PIL on stackoverflow, I get:

![Screenshot from 2019-07-02 15-00-30](https://user-images.githubusercontent.com/34352567/60502032-a1a10a00-9cda-11e9-8588-6faacfa2f935.png)

So PIL is basically not in working stage, Pillow is its alternative.

**Comment by rajeshsharma98** [comment]
Yes i also heard that.
Error got removed in my computer after installing Pillow-6.0.0 { so pillow is its alternative }
You may also want to try this command: sudo apt-get install python3-pil python3-pil.imagetk

**Comment by rpotter12** [comment]
No, it is not working for me

**Comment by rajeshsharma98** [comment]
Comment this line { from PIL import Image, ImageTk } in the code(login_register.py) and then try again.

**Comment by rajeshsharma98** [comment]
Are you receiving the same issue as mentioned earlier by you, have you tried installing pillow (and do check its version) ?
